name = "Ephemeral"
author = "Pyfish"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a518b4a49cbebc495349c0691c5423bd068616e9446c28f4f07ee2c9e3d86c1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
