name = "Ephemeral"
author = "Pyfish"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17ad07a50c0437ab9e29f027f0e1ee1865f2ecd6bc62f46f3a479bf6e04d142b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
