name = "Ephemeral"
author = "Pyfish"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50aa8bbb8fb1198f20648ed725caf283953ee49821a3397e5f0d3f6afd68ae89"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
